{
  bind=[
    "Super, C, exec, gnome-calculator"
    "Super, Return, exec, foot"
    "Super, E, exec, nautilus --new-window"
    "Super, W, exec, bash -c 'flatpak run com.vivaldi.Vivaldi'"
    "Super, X, exec, kate"
    "Super, T, exec, telegram-desktop"
    "Super, I, exec, XDG_CURRENT_DESKTOP=\"gnome\" gnome-control-center"
    "Control+Super, V, exec, pavucontrol"
    "Control+Super+Shift, V, exec, easyeffects"
    "Control+Shift, Escape, exec, gnome-system-monitor"
    "Super, Period, exec, pkill fuzzel || ~/.local/bin/fuzzel-emoji"
    "Super, Q, killactive,"
    "Super+Alt, Space, togglefloating,"
    ", Print, exec, ~/.config/ags/scripts/grimblast.sh --freeze copy area"
    "Super+Alt, R, exec, ~/.config/ags/scripts/record-script.sh"
    "Control+Alt, R, exec, ~/.config/ags/scripts/record-script.sh --fullscreen"
    "Super+Shift+Alt, R, exec, ~/.config/ags/scripts/record-script.sh --fullscreen-sound"
    "Super+Shift, C, exec, hyprpicker -a"
    "Super, V, exec, pkill fuzzel || cliphist list | fuzzel --dmenu | cliphist decode | wl-copy"
    "Control+Super+Shift,S,exec,grim -g \"$(slurp $SLURP_ARGS)\" \"tmp.png\" && tesseract -l rus+eng \"tmp.png\" - | wl-copy && rm \"tmp.png\""
    "Super, L, exec, loginctl lock-session"
    "Control+Super, Slash, exec, pkill anyrun || anyrun"
    "Control+Super, T, exec, ~/.config/ags/scripts/color_generation/switchwall.sh"
    "Control+Alt, Slash, exec, ags run-js 'cycleMode();'"
    "Super, Tab, exec, ags -t 'overview'"
    "Super, Slash, exec, bash -c 'for ((i=0; i<$(hyprctl monitors -j | jq length); i++)); do ags -t \"cheatsheet\"\"$i\"; done'"
    "Super, B, exec, ags -t 'sideleft'"
    "Super, A, exec, ags -t 'sideleft'"
    "Super, O, exec, ags -t 'sideleft'"
    "Super, N, exec, ags -t 'sideright'"
    "Super, M, exec, ags run-js 'openMusicControls.value = (!mpris.getPlayer() ? false : !openMusicControls.value);'"
    "Super, Comma, exec, ags run-js 'openColorScheme.value = true; Utils.timeout(2000, () => openColorScheme.value = false);'"
    "Super, K, exec, bash -c 'for ((i=0; i<$(hyprctl monitors -j | jq length); i++)); do ags -t \"osk\"\"$i\"; done'"
    "Control+Alt, Delete, exec, bash -c 'for ((i=0; i<$(hyprctl monitors -j | jq length); i++)); do ags -t \"session\"\"$i\"; done'"
    "Control+Super, G, exec, bash -c 'for ((i=0; i<$(hyprctl monitors -j | jq length); i++)); do ags -t \"crosshair\"\"$i\"; done'"
    "Super+Alt, f12, exec, notify-send 'Test notification' \"Here's a really long message to test truncation and wrapping\\nYou can middle click or flick this notification to dismiss it!\" -a 'Shell' -A \"Test1=I got it!\" -A \"Test2=Another action\" -t 5000"
    "Super+Alt, Equal, exec, notify-send \"Urgent notification\" \"Ah hell no\" -u critical -a 'Hyprland keybind'"
    "Control+Super, left, movewindow, l"
    "Control+Super, right, movewindow, r"
    "Control+Super, up, movewindow, u"
    "Control+Super, down, movewindow, d"
    "Control+Super+Alt, left, movewindow, l"
    "Control+Super+Alt, right, movewindow, r"
    "Control+Super+Alt, up, movewindow, u"
    "Control+Super+Alt, down, movewindow, d"
    "Control+Super+Shift, left, movewindow, l"
    "Control+Super+Shift, right, movewindow, r"
    "Control+Super+Shift, up, movewindow, u"
    "Control+Super+Shift, down, movewindow, d"
    "Control+Super, Space, togglesplit"
    "Super, P, pin"
    "Super, Left, movefocus, l"
    "Super, Right, movefocus, r"
    "Super, Up, movefocus, u"
    "Super, Down, movefocus, d"
    "Super, BracketLeft, workspace, -1"
    "Super, BracketRight, workspace, +1"
    "Super+Shift, Right, movetoworkspace, +1"
    "Super+Shift, Left, movetoworkspace, -1"
    "Super+Shift, BracketLeft, movetoworkspace, -1"
    "Super+Shift, BracketRight, movetoworkspace, +1"
    "Super, F, fullscreen, 0"
    "Super, D, fullscreen, 1"
    "Super+Shift, D, pseudo"
    "Super, 1, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh workspace 1"
    "Super, 2, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh workspace 2"
    "Super, 3, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh workspace 3"
    "Super, 4, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh workspace 4"
    "Super, 5, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh workspace 5"
    "Super, 6, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh workspace 6"
    "Super, 7, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh workspace 7"
    "Super, 8, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh workspace 8"
    "Super, 9, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh workspace 9"
    "Super, 0, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh workspace 10"
    "Super, S, togglespecialworkspace,"
    "Super+Alt, Left, workspace, -1"
    "Super+Alt, Right, workspace, +1"
    "Alt, Tab, cyclenext"
    "Alt, Tab, bringactivetotop,"   # bring it to the top
    "Control+Super, Backslash, resizeactive, exact 640 480"
    "Super+Shift, 1, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh movetoworkspacesilent 1"
    "Super+Shift, 2, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh movetoworkspacesilent 2"
    "Super+Shift, 3, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh movetoworkspacesilent 3"
    "Super+Shift, 4, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh movetoworkspacesilent 4"
    "Super+Shift, 5, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh movetoworkspacesilent 5"
    "Super+Shift, 6, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh movetoworkspacesilent 6"
    "Super+Shift, 7, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh movetoworkspacesilent 7"
    "Super+Shift, 8, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh movetoworkspacesilent 8"
    "Super+Shift, 9, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh movetoworkspacesilent 9"
    "Super+Shift, 0, exec, ~/.config/ags/scripts/hyprland/workspace_action.sh movetoworkspacesilent 10"
    "Super+Shift, S, movetoworkspacesilent, special"
    "Super, mouse_up, workspace, +1"
    "Super, mouse_down, workspace, -1"
    "Control+Super, mouse_up, workspace, +1"
    "Control+Super, mouse_down, workspace, -1"
  ];

  bindl=[
    "Super+Shift, N, exec, playerctl next || playerctl position `bc <<< \"100 * $(playerctl metadata mpris:length) / 1000000 / 100\"`"
    ",XF86AudioNext, exec, playerctl next || playerctl position `bc <<< \"100 * $(playerctl metadata mpris:length) / 1000000 / 100\"`"
    "Super+Shift, B, exec, playerctl previous"
    "Super+Shift, P, exec, playerctl play-pause"
    ",XF86AudioPlay, exec, playerctl play-pause"
    ", XF86AudioMute, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 0% && ags run-js 'indicator.popup(1);'"
    "Super+Shift,M,   exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 0% && ags run-js 'indicator.popup(1);'"
    "Super+Shift, L, exec, loginctl suspend"
  ];

  bindm = [
    "Super, mouse:272, movewindow"
    "Super, mouse:273, resizewindow"
    "Super, Z, movewindow"
  ];

  bindir = [
    "Super, Super_L, exec, ags -t 'overview'"
  ];

  bindle = [
    "Alt, I, exec, ydotool key 103:1 103:0"
    "Alt, K, exec, ydotool key 108:1 108:0"
    "Alt, J, exec, ydotool key 105:1 105:0"
    "Alt, L, exec, ydotool key 106:1 106:0"
    ", XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+ && ags run-js 'indicator.popup(1);'"
    ", XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && ags run-js 'indicator.popup(1);'"
    ", XF86MonBrightnessUp, exec, ags run-js 'brightness.screen_value += 0.05; indicator.popup(1);'"
    ", XF86MonBrightnessDown, exec, ags run-js 'brightness.screen_value -= 0.05; indicator.popup(1);'"
  ];

  binde = [
    "Super, Minus, splitratio, -0.1"
    "Super, Equal, splitratio, 0.1"
    "Super, Semicolon, splitratio, -0.1"
    "Super, Apostrophe, splitratio, 0.1"
  ];

  bindr = [
    "Control+Super, R, exec, ags -q; ags &"
    "Control+Super+Alt, R, exec, hyprctl reload; killall ags ydotool; ags &"
  ];
}